# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blogs
    url: /#blogs
    weight: 11
  - name: Photos
    url: /#photos
    weight: 12
  - name: Testimonials
    url: /#testimonials
    weight: 13
  - name: Experience
    url: experience/
    weight: 20
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
